/// Maps common country names / aliases to IANA timezone IDs
/// for intent-based search (e.g., "India" -> "Asia/Kolkata")
const Map<String, List<String>> countryTimezoneMap = {
  'india': ['Asia/Kolkata'],
  'usa': ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles'],
  'united states': ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles'],
  'uk': ['Europe/London'],
  'united kingdom': ['Europe/London'],
  'britain': ['Europe/London'],
  'england': ['Europe/London'],
  'japan': ['Asia/Tokyo'],
  'china': ['Asia/Shanghai'],
  'australia': ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Perth'],
  'germany': ['Europe/Berlin'],
  'france': ['Europe/Paris'],
  'canada': ['America/Toronto', 'America/Vancouver', 'America/Edmonton'],
  'brazil': ['America/Sao_Paulo'],
  'russia': ['Europe/Moscow'],
  'south korea': ['Asia/Seoul'],
  'korea': ['Asia/Seoul'],
  'singapore': ['Asia/Singapore'],
  'uae': ['Asia/Dubai'],
  'dubai': ['Asia/Dubai'],
  'saudi': ['Asia/Riyadh'],
  'saudi arabia': ['Asia/Riyadh'],
  'italy': ['Europe/Rome'],
  'spain': ['Europe/Madrid'],
  'netherlands': ['Europe/Amsterdam'],
  'holland': ['Europe/Amsterdam'],
  'turkey': ['Europe/Istanbul'],
  'mexico': ['America/Mexico_City'],
  'argentina': ['America/Argentina/Buenos_Aires'],
  'south africa': ['Africa/Johannesburg'],
  'egypt': ['Africa/Cairo'],
  'israel': ['Asia/Jerusalem'],
  'thailand': ['Asia/Bangkok'],
  'vietnam': ['Asia/Ho_Chi_Minh'],
  'indonesia': ['Asia/Jakarta'],
  'malaysia': ['Asia/Kuala_Lumpur'],
  'philippines': ['Asia/Manila'],
  'pakistan': ['Asia/Karachi'],
  'bangladesh': ['Asia/Dhaka'],
  'sri lanka': ['Asia/Colombo'],
  'nepal': ['Asia/Kathmandu'],
  'new zealand': ['Pacific/Auckland'],
  'nz': ['Pacific/Auckland'],
  'ireland': ['Europe/Dublin'],
  'portugal': ['Europe/Lisbon'],
  'switzerland': ['Europe/Zurich'],
  'sweden': ['Europe/Stockholm'],
  'norway': ['Europe/Oslo'],
  'denmark': ['Europe/Copenhagen'],
  'finland': ['Europe/Helsinki'],
  'poland': ['Europe/Warsaw'],
  'greece': ['Europe/Athens'],
  'hawaii': ['Pacific/Honolulu'],
};

/// Maps popular city names to IANA timezone IDs
const Map<String, List<String>> cityTimezoneMap = {
  // Americas
  'miami': ['America/New_York'],
  'new york': ['America/New_York'],
  'nyc': ['America/New_York'],
  'boston': ['America/New_York'],
  'atlanta': ['America/New_York'],
  'washington': ['America/New_York'],
  'philadelphia': ['America/New_York'],
  'detroit': ['America/New_York'],
  'chicago': ['America/Chicago'],
  'dallas': ['America/Chicago'],
  'houston': ['America/Chicago'],
  'austin': ['America/Chicago'],
  'minneapolis': ['America/Chicago'],
  'denver': ['America/Denver'],
  'phoenix': ['America/Phoenix'],
  'salt lake': ['America/Denver'],
  'los angeles': ['America/Los_Angeles'],
  'la': ['America/Los_Angeles'],
  'san francisco': ['America/Los_Angeles'],
  'sf': ['America/Los_Angeles'],
  'seattle': ['America/Los_Angeles'],
  'portland': ['America/Los_Angeles'],
  'las vegas': ['America/Los_Angeles'],
  'san diego': ['America/Los_Angeles'],
  'anchorage': ['America/Anchorage'],
  'honolulu': ['Pacific/Honolulu'],
  'toronto': ['America/Toronto'],
  'montreal': ['America/Toronto'],
  'ottawa': ['America/Toronto'],
  'vancouver': ['America/Vancouver'],
  'calgary': ['America/Edmonton'],
  'edmonton': ['America/Edmonton'],
  'mexico city': ['America/Mexico_City'],
  'cancun': ['America/Cancun'],
  'sao paulo': ['America/Sao_Paulo'],
  'rio': ['America/Sao_Paulo'],
  'buenos aires': ['America/Argentina/Buenos_Aires'],
  'bogota': ['America/Bogota'],
  'lima': ['America/Lima'],
  'santiago': ['America/Santiago'],
  // Europe
  'london': ['Europe/London'],
  'paris': ['Europe/Paris'],
  'berlin': ['Europe/Berlin'],
  'munich': ['Europe/Berlin'],
  'frankfurt': ['Europe/Berlin'],
  'amsterdam': ['Europe/Amsterdam'],
  'brussels': ['Europe/Brussels'],
  'madrid': ['Europe/Madrid'],
  'barcelona': ['Europe/Madrid'],
  'rome': ['Europe/Rome'],
  'milan': ['Europe/Rome'],
  'zurich': ['Europe/Zurich'],
  'geneva': ['Europe/Zurich'],
  'vienna': ['Europe/Vienna'],
  'prague': ['Europe/Prague'],
  'warsaw': ['Europe/Warsaw'],
  'stockholm': ['Europe/Stockholm'],
  'oslo': ['Europe/Oslo'],
  'copenhagen': ['Europe/Copenhagen'],
  'helsinki': ['Europe/Helsinki'],
  'dublin': ['Europe/Dublin'],
  'lisbon': ['Europe/Lisbon'],
  'athens': ['Europe/Athens'],
  'istanbul': ['Europe/Istanbul'],
  'moscow': ['Europe/Moscow'],
  'bucharest': ['Europe/Bucharest'],
  'budapest': ['Europe/Budapest'],
  'kiev': ['Europe/Kiev'],
  'kyiv': ['Europe/Kiev'],
  // Asia
  'dubai': ['Asia/Dubai'],
  'abu dhabi': ['Asia/Dubai'],
  'riyadh': ['Asia/Riyadh'],
  'doha': ['Asia/Qatar'],
  'mumbai': ['Asia/Kolkata'],
  'delhi': ['Asia/Kolkata'],
  'bangalore': ['Asia/Kolkata'],
  'chennai': ['Asia/Kolkata'],
  'hyderabad': ['Asia/Kolkata'],
  'kolkata': ['Asia/Kolkata'],
  'karachi': ['Asia/Karachi'],
  'lahore': ['Asia/Karachi'],
  'dhaka': ['Asia/Dhaka'],
  'kathmandu': ['Asia/Kathmandu'],
  'colombo': ['Asia/Colombo'],
  'bangkok': ['Asia/Bangkok'],
  'singapore': ['Asia/Singapore'],
  'kuala lumpur': ['Asia/Kuala_Lumpur'],
  'jakarta': ['Asia/Jakarta'],
  'manila': ['Asia/Manila'],
  'ho chi minh': ['Asia/Ho_Chi_Minh'],
  'saigon': ['Asia/Ho_Chi_Minh'],
  'hong kong': ['Asia/Hong_Kong'],
  'shanghai': ['Asia/Shanghai'],
  'beijing': ['Asia/Shanghai'],
  'shenzhen': ['Asia/Shanghai'],
  'taipei': ['Asia/Taipei'],
  'seoul': ['Asia/Seoul'],
  'tokyo': ['Asia/Tokyo'],
  'osaka': ['Asia/Tokyo'],
  // Africa & Oceania
  'cairo': ['Africa/Cairo'],
  'johannesburg': ['Africa/Johannesburg'],
  'cape town': ['Africa/Johannesburg'],
  'nairobi': ['Africa/Nairobi'],
  'lagos': ['Africa/Lagos'],
  'casablanca': ['Africa/Casablanca'],
  'sydney': ['Australia/Sydney'],
  'melbourne': ['Australia/Melbourne'],
  'brisbane': ['Australia/Brisbane'],
  'perth': ['Australia/Perth'],
  'auckland': ['Pacific/Auckland'],
  'wellington': ['Pacific/Auckland'],
  'fiji': ['Pacific/Fiji'],
};

/// Common timezone abbreviation mappings
const Map<String, List<String>> abbreviationMap = {
  'est': ['America/New_York'],
  'edt': ['America/New_York'],
  'cst': ['America/Chicago'],
  'cdt': ['America/Chicago'],
  'mst': ['America/Denver'],
  'mdt': ['America/Denver'],
  'pst': ['America/Los_Angeles'],
  'pdt': ['America/Los_Angeles'],
  'gmt': ['Europe/London'],
  'bst': ['Europe/London'],
  'cet': ['Europe/Berlin'],
  'cest': ['Europe/Berlin'],
  'ist': ['Asia/Kolkata'],
  'jst': ['Asia/Tokyo'],
  'cst china': ['Asia/Shanghai'],
  'aest': ['Australia/Sydney'],
  'aedt': ['Australia/Sydney'],
  'nzst': ['Pacific/Auckland'],
  'sgt': ['Asia/Singapore'],
  'hkt': ['Asia/Hong_Kong'],
  'kst': ['Asia/Seoul'],
};
